datasets:
  - imu: IMU_X001_small.dat
    gnss: GNSS_X001_small.csv
  - imu: IMU_X002_small.dat
    gnss: GNSS_X002_small.csv
  - imu: IMU_X003_small.dat
    gnss: GNSS_X002_small.csv
methods:
  - TRIAD
