[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "imu-gnss-fusion"
version = "0.1.0"
description = "GNSS-IMU Fusion tools"
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["Python"]
exclude = ["tests"]
