function task5_plot_comparison(run_id)
%TASK5_PLOT_COMPARISON Create frame comparison plots for Kalman filter results.
%   TASK5_PLOT_COMPARISON(RUN_ID) expects the base workspace to contain
%   variables ``t_kf``, ``pos_kf_TRIAD``, ``pos_kf_Davenport`` and
%   ``pos_kf_SVD`` generated by ``Task_5`` for each method.  Reference frame
%   information ``ref_lat``, ``ref_lon``, ``ref_r0`` and ``C_B_N_ref`` must
%   also be present.  The function writes four figures to
%   ``results/RUN_ID/`` with filenames following the pattern
%   ``<RUN_ID>_task5_<FRAME>_comparison.{pdf,png}``.
%
%   Example:
%       task5_plot_comparison('IMU_X001_GNSS_X001')
%
%   See also: plot_frame_comparison, Task_5

    if nargin < 1 || isempty(run_id)
        error('task5_plot_comparison:MissingRunID', 'RUN_ID is required');
    end

    results_dir = get_results_dir();
    out_dir = fullfile(results_dir, run_id);
    if ~exist(out_dir,'dir'); mkdir(out_dir); end

    t = evalin('base','t_kf');
    pos_TRIAD = evalin('base','pos_kf_TRIAD');
    pos_Davenport = evalin('base','pos_kf_Davenport');
    pos_SVD = evalin('base','pos_kf_SVD');
    ref_lat = evalin('base','ref_lat');
    ref_lon = evalin('base','ref_lon');
    ref_r0  = evalin('base','ref_r0');
    C_B_N_ref = evalin('base','C_B_N_ref');
    C_N_B_ref = C_B_N_ref';
    C_ECEF_to_NED = compute_C_ECEF_to_NED(ref_lat, ref_lon);
    C_NED_to_ECEF = C_ECEF_to_NED';

    data_sets = {pos_TRIAD', pos_Davenport', pos_SVD'};
    labels = {'KF-TRIAD','KF-Davenport','KF-SVD'};
    prefix = fullfile(out_dir, [run_id '_task5']);

    plot_frame_comparison(t, data_sets, labels, 'NED', prefix);

    data_ecef = {C_NED_to_ECEF*pos_TRIAD'+ref_r0, ...
                 C_NED_to_ECEF*pos_Davenport'+ref_r0, ...
                 C_NED_to_ECEF*pos_SVD'+ref_r0};
    plot_frame_comparison(t, data_ecef, labels, 'ECEF', prefix);

    data_body = {C_N_B_ref*pos_TRIAD', C_N_B_ref*pos_Davenport', C_N_B_ref*pos_SVD'};
    plot_frame_comparison(t, data_body, labels, 'BODY', prefix);

    plot_frame_comparison(t, data_sets, labels, 'Mixed', prefix);
end
