function s = default_cfg()
%DEFAULT_CFG  Central place for run-time policy (no hidden defaults in tasks).
addpath(fullfile(fileparts(fileparts(mfilename('fullpath'))), 'src', 'utils'));
p = project_paths();
s = struct();
s.dataset_id = '';        % must be set by caller
s.method     = '';        % must be set by caller
s.imu_file   = '';
s.gnss_file  = '';
s.truth_file = '';

s.paths = p;

s.plots = struct( ...
    'popup_figures', false, ...
    'save_pdf',      false, ...
    'save_png',      false);

% Gravity aiding defaults (can be overridden by caller)
s.gaid = struct( ...
    'enabled',        true, ...
    'fc_hz',          0.4, ...
    'sigma_dir_deg',  3.0, ...
    'max_dev_g',      0.15, ...
    'max_gyro_dps',   5.0, ...
    'min_speed_mps',  0.0);

% Yaw (course-over-ground) aiding
s.yawaid = struct( ...
    'enabled',        true, ...
    'min_speed_mps',  0.02, ... % FIX: allow yaw-aid at very low speed
    'sigma_yaw_deg',  5.0, ...
    'max_gyro_dps',   15.0, ...
    'gate_deg',       25.0);

% ZUPT detection configuration (Task-5 liftoff logic)
s.zupt = struct( ...
    'acc_movstd_thresh', 0.15, ...
    'min_pre_lift_s',    5, ...
    'speed_thresh_mps',  0.30);

% Lever arm (IMU->GNSS antenna) in body frame [m]
s.lever_arm = struct( ...
    'enabled',        false, ...
    'r_b',            [0.0, 0.0, 0.0]);

% Time alignment for measurements (Task-5)
s.time_align = struct( ...
    'apply',          false, ...
    'dt_s',           0.0);
end
