name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 15 * * 1'

permissions:
  contents: read
  security-events: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/python:0-3.10
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements-dev.txt -r requirements.txt
      - name: Run tests
        run: pytest -q
      - name: MATLAB smoke test
        run: pytest -q tests/test_pipeline_smoke.py
  codeql:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, actions]
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: none
      - uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"
