name: CI
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/python:0-3.10
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: make test
      - name: Run MATLAB smoke test
        run: pytest -q tests/test_pipeline_smoke.py
