name: CI & Security

permissions:
  contents: read          # needed to checkout
  security-events: write  # needed for CodeQL upload
  packages: read          # needed for any private packs
  actions: read           # read-only for actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 15 * * 1'  # every Monday at 15:15 UTC

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python deps
        run: pip install -r requirements-dev.txt -r requirements.txt
      - name: Run Python tests
        run: pytest -q
      - name: Run MATLAB smoke test
        run: pytest -q tests/test_pipeline_smoke.py

  codeql:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
          - actions
          - python
        build-mode:
          - none
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3
