name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 15 * * 1'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements-dev.txt -r requirements.txt
      - name: Run flake8
        run: flake8 --config=.flake8
      - name: Run tests
        run: pytest -q
      - name: MATLAB smoke test
        run: pytest -q tests/test_pipeline_smoke.py
