name: CI
permissions:
  contents: read
  security-events: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 15 * * 1'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/python:0-3.10
    steps:
      - uses: actions/checkout@v4
      - name: Get Python version
        id: python-version
        run: |
          echo "version=$(python -c 'import sys; print("%s.%s" % (sys.version_info.major, sys.version_info.minor))')" >> "$GITHUB_OUTPUT"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ steps.python-version.outputs.version }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ steps.python-version.outputs.version }}-
      - name: Install dependencies
        run: pip install -r requirements-dev.txt -r requirements.txt
      - name: Run tests
        run: pytest -q
      - name: MATLAB smoke test
        run: pytest -q tests/test_pipeline_smoke.py
  codeql:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, actions]
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: none
      - uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"
