name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository so the workflow can access it
      - uses: actions/checkout@v4

      # Set up a Python 3.x environment
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install project dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Install flake8 separately for linting
      - name: Install flake8
        run: pip install flake8

      # Run the unit tests
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Lint the codebase
      - name: Run flake8
        run: flake8 .
